opcua:
  serverURL: "opc.tcp://192.168.26.135:4840"
  securityPolicy: "None"
  securityMode: "None"
variables:
  - name: "ActualPos"
    type: "u32"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: ActualPos

  - name: "ActualVelocity"
    type: "float"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: ActualVelocity

  - name: "EDRK_Local"
    type: "float"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: EDRK_Local

  - name: "EDRK_Off"
    type: "float"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: EDRK_Off

  - name: "EDRK_On"
    type: "float"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: EDRK_On

  - name: "OperationMode"
    type: "u32"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: OperationMode

  - name: "TargetPos"
    type: "u32"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: TargetPos

  - name: "TargetPosInc"
    type: "float"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: TargetPosInc

  - name: "VFD1_State"
    type: "u32"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: VFD1_State

  - name: "VFD2_State"
    type: "u32"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: VFD2_State

  - name: "VFD3_State"
    type: "u32"
    dir: "HAL_IN"
    namespaceIndex: 0
    identifier: VFD3_State
    
    